collections:
  people:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar