name: iCal Processor

on:
  push:
    branches:
      - main  # Or master, depending on your branch name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby and install Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use a recent Ruby version
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"

      - name: Process and Finalize ICS File
        run: |
          # 1. Read the Jekyll-built file containing placeholders
          RAW_CONTENT=$(cat _site/assets/CAUSE_calendar.ics.liquid)
          
          # 2. Perform the CR+LF and folding replacement using sed.
          #    \r\n is the literal iCalendar line ending.
          #    \r\n[space] is the literal iCalendar folding sequence.
          PROCESSED_CONTENT=$(echo "$RAW_CONTENT" | sed 's/##NEWLINE##/\r\n /g')

          # 3. Write the final, corrected .ics file to the published folder (_site)
          echo "$PROCESSED_CONTENT" > _site/assets/CAUSE_calendar.ics
          
          # 4. Remove the intermediate .liquid file
          rm _site/calendar.ics.liquid

      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./_site
      #    # Ensure .ics files are included
      #    exclude_assets: '.sass-cache,Rakefile,README.md'
      #    #cname: your-custom-domain.com # Only if you use a custom domain
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
